services:
  - type: web
    name: education-backend-nosql
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: education_platform
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /api/health
    domains:
      - education-backend-nosql.onrender.com
